CREATE DATABASE KIRILL_ALEXEENKO;
GO

USE KIRILL_ALEXEENKO;
GO

CREATE SCHEMA sales;
GO

CREATE SCHEMA persons;
GO

CREATE TABLE sales.Orders (OrderNum INT NULL);
GO

BACKUP DATABASE KIRILL_ALEXEENKO TO DISK='D:\УНИВЕР\7 семестр\БД\DB_Epam\Lab1\KIRILL_ALEXEENKO.bak';
GO

USE master
DROP DATABASE KIRILL_ALEXEENKO;
GO

RESTORE DATABASE KIRILL_ALEXEENKO FROM DISK='D:\УНИВЕР\7 семестр\БД\DB_Epam\Lab1\KIRILL_ALEXEENKO.bak';
GO